services:
  frontend:
    build: .
    ports:
      - "3000:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BACKEND_URL=http://host.docker.internal:8000
